config/routes.rb
# -*- encoding : utf-8 -*-
Applebeauty::Application.routes.draw do
  devise_for :users do
    get "logout" => "devise/sessions#destroy"
  end
  #root :to => 'high_voltage/pages#show', :id => 'welcome'

  resources :links do
    resources :photos
    collection do
      get "best_of_the_week"
      get "best_of_the_month"
      get "worst_of_all"
      get "best_of_all"
      get "appeal"
    end
    member do
      post "like"
      post "dislike"
    end
  end

  resources :pages do
    collection do
      get "welcome"
      get "sign_in"
    end
  end

  root :to => 'links#index'
end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id         :integer          not null, primary key
#  url        :string(255)
#  title      :string(255)
#  rate       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  clip       :string(255)
#  detail     :text(65535)
#  appeal     :boolean          default(FALSE)
#  link_type  :string(255)      default("daily")
#

# -*- encoding : utf-8 -*-
class Link < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  # attr_accessible :title, :body
  has_many :photos
  
  scope :recent, -> { order(:title => :desc)}

  acts_as_votable

  def previous
    query = Link.recent
    index = query.find_index(self)
    prev_id = query[index-1] || query.last
    return query.find(prev_id)
  end

  def next
    query = Link.recent
    index = query.find_index(self)
    next_id = query[index+1] || query.first
    return query.find(next_id)
  end

  def self.best_of_all
    order("rate desc").limit(10)
  end

  def self.best_of_the_month
    where("created_at between ? and ? and rate > 2", Date.today.beginning_of_month, Date.today.end_of_month).order("rate DESC").limit(5)
  end

  def self.best_of_the_week
    where("created_at between ? and ? and rate > 1", Date.today.beginning_of_week, Date.today.end_of_week).order("rate DESC").limit(5)
  end

  def self.worst_of_all
    where("rate < 0").order("rate asc").limit(10)
  end

  def self.appeal
    where("appeal = true").order("rate asc")  
  end

  def calculate_rate
    self.rate = self.get_likes.size - self.get_dislikes.size
    self.save
  end

  def up_vote_by_this_user(voter)
    if voter.voted_on?(self)
      return false
    else
      self.liked_by(voter)
      self.calculate_rate
      return true
    end 
  end

  def down_vote_by_this_user(voter)
    if voter.voted_on?(self)
      return false
    else
      self.disliked_by(voter)
      self.calculate_rate
      return true
    end 
  end

end

app/controllers/links_controller.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: links
#
#  id         :integer          not null, primary key
#  url        :string(255)
#  title      :string(255)
#  rate       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  clip       :string(255)
#  detail     :text(65535)
#  appeal     :boolean          default(FALSE)
#  link_type  :string(255)      default("daily")
#

class LinksController < ApplicationController

  before_filter :find_voter, :only => [:like, :dislike, :show]
  before_filter :search_object, :only => [:index, :show, :best_of_the_week, :best_of_the_month, :search, :worst_of_all, :appeal, :best_of_all]
  before_filter :find_link, :only => [:show, :like, :dislike]

  include ActionView::Helpers::SanitizeHelper

  def index

    if Link.first.present?
      set_page_image(Setting.domain + Link.last.photos.first.file.url) if Link.last.photos.first.file
      # @links = Link.all
      # @links = @links.paginate(:page => params[:page], :per_page => 18)
      if params[:q].present?
        @query_string = params[:q][:detail_cont]
        @links = @search.result.recent.paginate(:per_page => 30, :page => params[:page])
      else
        @todays_link = Link.recent.first
        @links = Link.recent.where("id <> ?", Link.recent.first.id)
        # @links = Link.recent.reject { |r| r.id == Link.recent.first.id }
        @links = @links.paginate(:per_page => 30, :page => params[:page])
      end

      respond_to do |format|
        format.html
        format.rss { render layout: false}
      end
    end
  end

  def show
    @link.calculate_rate
    set_page_title("#{@link.title}")
    set_page_description(strip_tags("#{@link.detail}"))
    set_page_keywords(@link.detail)
    set_page_image(Setting.domain + @link.photos.first.file.url) if @link.photos
    get_random_link(3)
    @next = @link.next
    @previous = @link.previous
  end

  def like
    if @link.up_vote_by_this_user(@voter)
      flash[:notice] = "感謝您神聖一票，已列入統計"
    else
      flash[:notice] = "您投過票囉"
    end
  end

  def dislike
    if @link.down_vote_by_this_user(@voter)
      flash[:notice] = "感謝您神聖一票，已列入統計"
    else
      flash[:notice] = "您投過票囉"
    end
  end

  def best_of_the_week
    set_page_title("本週精選")
    @links = Link.best_of_the_week
    if @links.empty?
      get_random_link(6)
    end
  end

  def best_of_the_month
    set_page_title("本月精選")
    @links = Link.best_of_the_month

    if @links.empty?
      get_random_link(6)
    end
  end

  def worst_of_all
    set_page_title("不要鬧")
    @links = Link.worst_of_all
  end

  def best_of_all
    set_page_title("累計人氣")
    @links = Link.best_of_all
  end

  def appeal
    set_page_title("上訴專區")
    @links = Link.appeal

    if @links.empty?
      get_random_link(3)
    end
  end

  protected

  def find_link
    @link = Link.friendly.find(params[:id])
  end

  def find_voter
    session[:voting_id] = request.remote_ip
    @voter = Session.find_or_create_by(:ip => session[:voting_id])
  end

  def search_object
    @search = Link.ransack(params[:q])
  end

  def get_random_link(num)
    @random_links = nil
    ids = Link.pluck(:id).shuffle[0..num-1]
    @random_links = Link.where(id: ids)
    return @random_links
  end
end

app/helpers/links_helper.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: links
#
#  id         :integer          not null, primary key
#  url        :string(255)
#  title      :string(255)
#  rate       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  clip       :string(255)
#  detail     :text(65535)
#  appeal     :boolean          default(FALSE)
#  link_type  :string(255)      default("daily")
#

module LinksHelper

  def render_link_date(link)
    link.title
  end

  def render_link_girl_name(link)
    link.detail = link.detail.gsub('<BR>', '<br>')
    if link.detail.index("暱稱：")
      tmp = link.detail.split("暱稱：").second
    elsif link.detail.index("本名：")
      tmp = link.detail.split("本名：").second
    elsif link.detail.index("姓名：")
      tmp = link.detail.split("姓名：").second
    else
      tmp = "神祕路人<br"
    end

    name = tmp.split("<br").first
    return name
  end

  def render_next_link
    s = ""
    # s += content_tag(:i, "",:class => "icon-arrow-left")
    # s += " 後一天"
    s += fa_icon("arrow-circle-o-left 2x", text: "")
    link_to(s.html_safe, @previous, :class => "btn btn-default left")
    # s.html_safe
  end

  def render_prev_link
    s = ""
    # s += "前一天 "
    # s += content_tag(:i, "",:class => "icon-arrow-right")
    s += fa_icon("arrow-circle-o-right 2x", text: "", right: true)
    link_to(s.html_safe, @next, :class => "btn btn-default right")

  end

  def render_link_title(link)
    if link.link_type == "daily"
      "今天我最美 #{link.title.gsub(/[^0-9]/, '')}"
    else
      "運動靚妹 #{link.title.gsub(/[^0-9]/, '')}"
    end
  end

  def render_link_photos_for_slide(link)
    if link.photos.present?
      s = ""

      link.photos.each do |photo|
        if photo == link.photos.first
          s += content_tag(:div, :class => "item active") do
            link_to(photo.file.url, :data => { :colorbox => true }) do
              image_tag(photo.file)
            end
          end
        else
          s += content_tag(:div, :class => "item") do
            link_to(photo.file.url, :data => { :colorbox => true }) do
              image_tag(photo.file)
            end
          end
        end
      end

      return s.html_safe
    else
      content_tag(:div, :class => "item active") do
        image_tag("/images/760x420.gif")
      end
    end
  end
end

app/views/links/_complain.html.erb
<div class="white-box" align="center">
  <h2>我要上訴</h2>
  <% if @link.photos.size > 1 %>
    <% @link.photos.each do |photo| %>
      
      <%= link_to(photo.file.url, :data => { :colorbox => true, :colorbox_height => "700px" }) do %>
        <%= image_tag(photo.file.tiny) %>
      <% end %>

    <% end %>
  <% end %>
  <% if current_user && current_user.admin? %>
  <%= link_to("Upload photo", new_link_photo_path(@link), :class => "btn btn-info") %>
  <% end %>
  <hr>
  <p>如果您看過這位正妹其它照片，深深認為她是被攝影師陷害的話，請 email 至 <%= mail_to("youngvoice.basement@gmail.com") %></p>
</div>

app/views/links/_image_box.html.erb
<!-- <div class="white-box" align="center">
  <%= link_to(@link.photos.first.file.url, :data => { :colorbox => true }) do %>
    <%= image_tag(@link.photos.first.file, :class => "main-img") %>
  <% end %>
</div> -->

<div class="img-polaroid slider">
  <div id="myCarousel" class="carousel slide">
      <!-- Carousel items -->
    <div class="carousel-inner">
      <%= render_link_photos_for_slide(@link) %>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev"><i class="icon-chevron-left"></i></a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next"><i class="icon-chevron-right"></i></a>
  </div>
</div>

app/views/links/_no_result.html.erb
  <div class="white-box" align="center">
    <br>
    <p>目前暫無統計結果，可能是投票數不足。</p>
    <br>
    <div class="row">
      <div class="col-xs-12">
        <div class="row">
        <%= render partial: "random_result" %>
        </div>
      </div>
    </div>
  </div>

app/views/links/_random_result.html.erb
        <% @random_links.each do |link| %>
          <div class="col-xs-12 col-sm-4 col-md-4 box">
            <%= link_to(link) do %>
              <div class="innerbox" align="center">
                <% if link.link_type == "sports" %>
                  <span class="label label-info label-large label-title complained"><%= render_link_title(link) %></span>
                <% else %>
                  <span class="label label-info label-large label-title"><%= render_link_title(link) %></span>
                <% end %>
                <div align="center">
                <%= image_tag(link.photos.first.file.tiny) %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>

app/views/links/_tool_box.html.erb
  <div class="toolbox" align="center">
    <%= render_next_link %>
    <%= render_prev_link %>
    <div class="vote-result">
      <% if @voter.voted_on?(@link) %>
        <div class="votes">
        覺得她正的共 <%= content_tag(:span, @link.get_likes.size, :class => "label label-info") %> 票<br>覺得不正的共 <%= content_tag(:span, @link.get_dislikes.size, :class => "label label-info") %> 票</div>
      <% else %>
        <div class="btn-group">
          <div class="hidden-xs">
            <%= link_to(fa_icon("thumbs-up", text: "她 我可以"), like_link_path(@link), :class => "btn btn-danger", :remote => true, :method => :post) %>
            <span class="btn btn-info check-result"><%= fa_icon("list") %> 沒意見，看結果</span>
            <%= link_to(fa_icon("thumbs-down", text: "不要鬧了!!"), dislike_link_path(@link), :class => "btn btn-inverse btn-warning", :remote => true, :method => :post) %>
          </div>
          <div class="visible-xs">
            <%= link_to(fa_icon("thumbs-up 2x"), like_link_path(@link), :class => "btn btn-danger", :remote => true, :method => :post) %>
            <span class="btn btn-info check-result"><%= fa_icon("list 2x") %></span>
            <%= link_to(fa_icon("thumbs-down 2x"), dislike_link_path(@link), :class => "btn btn-inverse btn-warning", :remote => true, :method => :post) %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/links/appeal.html.erb
<div class="row">
  <% if @links.present? %>
  <% @links.each_with_index do |link, i| %>
    <div class="col-xs-12">
      <div class="white-box">
        <div class="row">
          <div class="col-xs-8">
            <%= link_to(link_path(link)) do %>
              <% link.photos.each_with_index do |photo, j| %>
                <% if j < 3 %>
                  <%= image_tag(photo.file, :width => 200) %>
                <% end %>
              <% end %>
            <% end %>
          </div>
          <div class="col-xs-3">
            <br>
            <span class="girl-name"><%= render_link_girl_name(link) %></span>
            <div>
              <span class="red">好評指數 <%= link.rate %></span>
            </div>
            <div>
              <%= link.detail.html_safe %>
            </div>
          </div>
        </div>
      </div>
      <br>
    </div>
  <% end %>
  <% else %>
  <div class="col-xs-8 offset2">
  <%= render partial: "no_result" %>
  </div>
  <% end %>
</div>

app/views/links/best_of_all.html.erb
<div class="row">
  <% if @links.present? %>
  <% @links.each_with_index do |link, i| %>
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="white-panel shadow">
        <div class="row">
          <div class="col-xs-6">
            <%= link_to(link_path(link)) do %>
              <%= image_tag(link.photos.first.file, :width => 180) %>
            <% end %>
          </div>
          <div class="col-xs-6">
            <div class="github-fork-ribbon-wrapper right">
              <div class="github-fork-ribbon"><a href="">累計第 <%= i+1 %> 名</a></div>
            </div>
            <br>
            <span class="girl-name"><%= render_link_girl_name(link) %></span>
            <div>
              <span class="red">好評指數 <%= link.rate %></span>
            </div>
            <div>
              <%= link.detail.html_safe %>
            </div>
          </div>
        </div>
      </div>
      <br>
    </div>
  <% end %>
  <% else %>
  <div class="col-xs-12">
  <%= render partial: "no_result" %>
  </div>
  <% end %>
</div>

app/views/links/best_of_the_month.html.erb
<div class="row">
  <% if @links.present? %>
    <% @links.each_with_index do |link, i| %>
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <div class="white-panel shadow">
          <div class="row">
            <div class="col-xs-6">
              <%= link_to(link_path(link)) do %>
                <%= image_tag(link.photos.first.file, :width => 180) %>
              <% end %>
            </div>
            <div class="col-xs-6">
              <div class="github-fork-ribbon-wrapper right">
                <div class="github-fork-ribbon"><a href="">本月第 <%= i+1 %> 名</a></div>
              </div>
              <br>
              <span class="girl-name"><%= render_link_girl_name(link) %></span>
              <div>
                <span class="red">好評指數 <%= link.rate %></span>
              </div>
              <div>
                <%= link.detail.html_safe %>
              </div>
            </div>
          </div>
        </div>
        <br>
      </div>
    <% end %>
  <% else %>
  <div class="col-xs-12">
    <%= render partial: "no_result" %>
  </div>
  <% end %>
</div>

app/views/links/best_of_the_week.html.erb
<div class="row">
  <% if @links.present? %>
  <% @links.each_with_index do |link, i| %>
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="white-panel shadow">
        <div class="row">
          <div class="col-xs-6">
            <%= link_to(link_path(link)) do %>
              <%= image_tag(link.photos.first.file, :width => 180) %>
            <% end %>
          </div>
          <div class="col-xs-6">
            <div class="github-fork-ribbon-wrapper right">
              <div class="github-fork-ribbon"><a href="">本週第 <%= i+1 %> 名</a></div>
            </div>
            <br>
            <span class="girl-name"><%= render_link_girl_name(link) %></span>
            <div>
              <span class="red">好評指數 <%= link.rate %></span>
            </div>
            <div>
              <%= link.detail.html_safe %>
            </div>
          </div>
        </div>
      </div>
      <br>
    </div>
  <% end %>
  <% else %>
  <div class="col-xs-12">
  <%= render partial: "no_result" %>
  </div>
  <% end %>
</div>

app/views/links/dislike.js.erb
$("div.vote-result").replaceWith('<div class="votes">覺得她正的共 <%= content_tag(:span, @link.get_likes.size, :class => "label label-info") %> 票<br>覺得不正的共 <%= content_tag(:span, @link.get_dislikes.size, :class => "label label-info") %> 票</div>');
insertAutoDismissAlert('<%= escape_javascript(notice_message) %>');
<% flash[:notice] = nil %>

app/views/links/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="well" align="center">
      <h2><%= link_to("武漢肺炎最新情況", "https://news.google.com/search?q=%E6%AD%A6%E6%BC%A2%E8%82%BA%E7%82%8E&hl=zh-TW&gl=TW&ceid=TW%3Azh-Hant", target: "_blank") %></h2>
    </div>
  </div>
</div>
<% if @todays_link.present? %>
  <div class="row">
    <div class="col-xs-12">
      <div class="row transitions-enabled infinite-scroll clearfix has-gutters" id="masonry-container">
        <% if @query_string.nil? %>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 box todays">
            <%= link_to(@todays_link) do %>
              <div class="innerbox" align="center">
                <span class="label label-info label-large label-title today-label"><%= render_link_title(@todays_link) %></span>
                <div align="center">
                  <%= image_tag(@todays_link.photos.first.file) %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
        <% @links.each do |link| %>
          <div class="box others">
            <%= link_to(link) do %>
              <div class="innerbox" align="center">
                <span class="label label-info label-large label-title"><%= render_link_title(link) %></span>
                <div align="center">
                  <%= image_tag(link.photos.first.file.tiny) %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12" align="center">
      <%= will_paginate @links, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
<% end %>
<%= content_for :javascripts do %>
<script type="text/javascript">
$(function(){
  $('#masonry-container').masonry({
    itemSelector: '.box',
    columnWidth: function( containerWidth ) {
      return containerWidth / 6;
    },
    gutterWidth: 0
  });
})
// alert($( window ).width());

window.onload = function(){
  $('#masonry-container').masonry();
}
</script>
<% end %>

app/views/links/like.js.erb
$("div.vote-result").replaceWith('<div class="votes">覺得她正的共 <%= content_tag(:span, @link.get_likes.size, :class => "label label-info") %> 票<br>覺得不正的共 <%= content_tag(:span, @link.get_dislikes.size, :class => "label label-info") %> 票</div>');
insertAutoDismissAlert('<%= escape_javascript(notice_message) %>');
<% flash[:notice] = nil %>

app/views/links/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= render partial: "tool_box" %>
    <br>
  </div>
  <div class="col-xs-12 col-sm-4">
    <%= render partial: "image_box" %>
  </div>
  <div class="col-xs-12 col-sm-8">
    <div class="row">
      <div class="col-xs-12">
        <div class="white-box">
          <video controls>
            <source src="<%= @link.clip %>" type="video/mp4">
          </video>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-xs-12">
        <span class="btn btn-warning" id="toggleInfo">看基本資料</span>
        <% if @link.link_type == "daily" %>
          <%= link_to("打開蘋果日報「今天我最美」", @link.url, :class => "btn btn-danger", :target => "_blank") %>
        <% else %>
          <%= link_to("打開蘋果日報「運動靚妹」", @link.url, :class => "btn btn-danger", :target => "_blank") %>
        <% end %>
        <div class="white-box detail">
          <h4><%= render_link_date(@link) %> - <%= render_link_girl_name(@link) %></h4>
          <%= @link.detail.html_safe %>
          <br>
          <p>資料來源 - 蘋果日報 <%= render_link_date(@link) %></p>
        </div>
        
      </div>
    </div>
  </div>
  <div class="col-xs-12"><hr></div>
  <!-- <div class="col-xs-12">
    <div class="white-box">
      <div class="row">
        <div class="col-xs-12" align="center"><h3>隨機推薦</h3></div>
        <br>
        <%= render partial: "random_result" %>
      </div>
    </div>
  </div> -->
</div>
<%= content_for :javascripts do %>
  <script type="text/javascript">
  $(document).ready(function () {
    $('#myCarousel').oneCarousel({
      easeIn: 'rotateIn',
      interval: 5000,
      pause: 'hover'
    });
  });
    $(".check-result").click(function(){
      $("div.vote-result").replaceWith('<div class="votes">覺得她正的共 <%= content_tag(:span, @link.get_likes.size, :class => "label label-info") %> 票<br>覺得不正的共 <%= content_tag(:span, @link.get_dislikes.size, :class => "label label-info") %> 票</div>');
    })

    $("span#toggleInfo").click(function(){
      $("div.detail").slideToggle(500);
      // $("img.main-img").slideToggle(500);
    })


  </script>
<% end %>

app/views/links/worst_of_all.html.erb
<div class="row">
  <% @links.each_with_index do |link, i| %>
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="white-panel shadow">
        <div class="row">
          <div class="col-xs-6">
            <%= link_to(link_path(link)) do %>
              <%= image_tag(link.photos.first.file, :width => 180) %>
            <% end %>
          </div>
          <div class="col-xs-6">
            <br>
            <br>
            <span class="girl-name"><%= render_link_girl_name(link) %></span>
            <div>
              <span class="red">賣鬧指數 <%= link.rate.abs %></span>
            </div>
            <br>
            <div>
              <%= link.detail.html_safe %>
            </div>
          </div>
        </div>
      </div>
      <br>
    </div>
  <% end %>
</div>