config/routes.rb
# -*- encoding : utf-8 -*-
Applebeauty::Application.routes.draw do
  devise_for :users do
    get "logout" => "devise/sessions#destroy"
  end
  #root :to => 'high_voltage/pages#show', :id => 'welcome'

  resources :links do
    resources :photos
    collection do
      get "best_of_the_week"
      get "best_of_the_month"
      get "worst_of_all"
      get "best_of_all"
      get "appeal"
    end
    member do
      post "like"
      post "dislike"
    end
  end

  resources :pages do
    collection do
      get "welcome"
      get "sign_in"
    end
  end

  root :to => 'links#index'
end

app/views/common/_bootstrap_modal.html.erb
<div id="modal-from-dom" class="modal hide fade">

</div>

app/views/common/_facebook_js.erb
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : <%= Setting.facebook_app_id%>,
      xfbml      : true,
      version    : 'v2.6'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/zh_TW/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

app/views/common/_footer.html.erb
<footer class="footer" align="center">
  <%= render_list :class => "nav nav-pills pull-right" do |li|
      #li << link_to( "Link1", "#")
      #li << link_to( "Link2", "#")   
      #li << link_to( "Link3", "#")
      #li << link_to( "Link4", "#")
  end %>
  <p class="copyright">Copyright @2013-<%= Time.now.year %> <%= Setting.app_name %> All rights reserved. 資料來源 - 蘋果日報「今天我最美」</p>
</footer>

app/views/common/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= Setting.google_analytics_key %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/common/_menu.html.erb
<nav>
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <%= link_to(Setting.app_name, Setting.domain , :class => "brand" )%>
      </div>
      <div class="col-md-3">
        <%= render partial: "common/search_form" %>
      </div>
      <div class="col-md-5">
        <div class="menu-items">
          <%= link_to("本週精選",best_of_the_week_links_path, :class => "no-shadow") %> |
          <%= link_to("本月精選",best_of_the_month_links_path, :class => "no-shadow") %> |
          <%= link_to("累計人氣",best_of_all_links_path, :class => "no-shadow") %> |
          <%= link_to("不要鬧", worst_of_all_links_path, :class => "no-shadow") %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="social"><%=  fb_like(request.url) %></div>
      </div>
    </div>
  </div>
</nav>

app/views/common/_search_form.html.erb
<% if @search %>
<%= search_form_for @search, :url => links_path, :class => "form-inline", :method => :get do |f|%>
   <input type="text" name="q[detail_cont]" class="search-query form-control" value="<%= @query_string %>" placeholder="<%= @query_string ||   "Search ex. 咩咩, 32c" %>" />
<% end %> 
<% end %>
 

app/views/common/_user_nav.html.erb
<ul class="nav pills pull-right">
  <% if current_user %>    
    <li class="dropdown">
      <%= link_to "/account" , :class => "dropdown-toggle", :data => { :toogle => "dropdown" } do %>
        <%= current_user.email %>
      <% end %>
      <%= render_list :class => "dropdown-menu" do |li|
          li << link_to("Logout",destroy_user_session_path, :method => :delete )
      end %>
    </li>
  <% else %>
    <li> <%= link_to( "註冊" ,new_user_registration_path) %> </li>
    <li> <%= link_to( "登入", new_user_session_path )  %> </li>   
  <% end %>
</ul>